apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices
  namespace: argocd
spec:
  description: Microservices Lab Project
  sourceRepos:
    - 'https://github.com/matheus06/gitops-helm.git'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: microservices-dev
      server: https://kubernetes.default.svc
    - namespace: microservices-prod
      server: https://kubernetes.default.svc
    - namespace: microservices-ubuntu
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'batch'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'monitoring.coreos.com'
      kind: '*'
    - group: 'argoproj.io'
      kind: 'Application'
