apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/GITHUB_USERNAME/gitops-helm.git
    targetRevision: main
    path: argocd/apps/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
